name: Check environment
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Show environment
      run: env | sort
      shell: bash
    - name: Show github context
      run: echo '${{ toJson(github) }}'
      shell: bash
  windows:
    runs-on: windows-2019

    steps:
    - name: Default powershell
      run: $PSVersionTable
    - name: Explicit pwsh
      run: $PSVersionTable
      shell: pwsh
    - name: Explicit powershell
      run: $PSVersionTable
      shell: powershell
    - name: Command Prompt
      run: ver
      shell: cmd
    - name: Git for Windows
      run: env && cygpath -aw $SHELL
      shell: bash
