name: Check environment
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Show environment
      run: env | sort
      shell: bash
    - name: Show a current user
      run: id && cat /etc/passwd
      shell: bash
    - name: Show github context
      run: echo '${{ toJson(github) }}'
      shell: bash
  windows:
    runs-on: windows-2019

    steps:
    - name: Default powershell
      run: $PSVersionTable
    - name: Explicit pwsh
      run: $PSVersionTable
      shell: pwsh
    - name: Explicit powershell
      run: $PSVersionTable
      shell: powershell
    - name: Command Prompt
      run: ver
      shell: cmd
    - name: Git for Windows
      run: env && cygpath -aw $SHELL
      shell: bash
  git-for-windows:
    runs-on: windows-2019
    steps:
    - name: Cehck git for windows environment in details
      run: |
        bash --version
        cygpath -aw /
        which -a make
        tty || true  # Check tty
