name: Check environment
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Show environment
      run: env | sort
      shell: bash
    - name: Show github context
      run: echo '${{ toJson(github) }}'
      shell: bash
