name: Check a pull request event

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - closed

jobs:
  info:
    runs-on: ubuntu-20.04
    steps:
    - name: Show environment
      run: env | grep -i github | sort | tee env.txt
    - name: Show github context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT" | jq 'del(.token)' | tee github_context.json
    - name: Show event object
      env:
        EVENT_OBJECT: ${{ toJSON(github.event) }}
      run: echo "$EVENT_OBJECT" | tee pull_request_event.json
    - uses: actions/upload-artifact@v2
      with:
        name: info
        path: |
          *.txt
          *.json
