name: Trial
on: [push]

runs-on: ${{ matrix.os }}
strategy:
  matrix:
    os: [ubuntu-latest, macOS-latest, windows-latest]

jobs:
  build:
    steps:
    - name: Run a one-line script
      run: echo Hello, world! at $(date)
      shell: bash
