name: Trial
on: [push]



jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Run a one-line script
      run: echo Hello, world! at $(date)
      shell: bash
