name: Trial
on: [push]



jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Show environment
      run: env | sort
      shell: bash

    - name: Run a one-line script
      run: |
        case "$RUNNER_OS" in
          Linux)
            BINARY_URL=https://github.com/shyiko/jabba/releases/download/${JABBA_VERSION}/jabba-${JABBA_VERSION}-linux-amd64
            ;;
          macOS)
            BINARY_URL=https://github.com/shyiko/jabba/releases/download/${JABBA_VERSION}/jabba-${JABBA_VERSION}-darwin-amd64
            ;;
          Windows)
            BINARY_URL=https://github.com/shyiko/jabba/releases/download/${JABBA_VERSION}/jabba-${JABBA_VERSION}-windows-amd64.exe
            ;;
        esac
        curl -L -o jabba "$BINARY_URL"
        chmod +x jabba
        ./jabba --version
        ./jabba install "$JAVA_VERSION"
        JAVA_HOME=$(./jabba which "$JAVA_VERSION")
        PATH=$(./jabba which "$JAVA_VERSION")/bin:$PATH
        java -version
      env:
        JABBA_VERSION: 0.11.2
        JAVA_VERSION: zulu@1.8
      shell: 'bash --noprofile --norc -eux -o pipefail {0}'
