name: Visual Studio components
on:
  workflow_dispatch:

jobs:
  # https://github.com/actions/runner-images/issues/9701
  add_component:
    runs-on: windows-2022
    steps:
      - name: List installed components
        run: (Get-VSSetupInstance).Packages | Format-Table -AutoSize
      - name: Install components
        run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          $componentsToRemove= @(
            "Microsoft.VisualStudio.Component.VC.140"
          )
          [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --add " +  $_}
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
          # should be run twice
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
      - name: List installed components again
        run: (Get-VSSetupInstance).Packages | Format-Table -AutoSize
