name: Visual Studio components
on:
  workflow_dispatch:

jobs:
  # https://github.com/actions/runner-images/issues/9701
  add_component:
    runs-on: windows-2022
    env:
      VS_INSTALLER: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe'
      VS_INSTALL_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise'
    steps:
      - name: Install components
        run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          $componentsToRemove= @(
            "Microsoft.VisualStudio.Component.VC.14.39.17.9.ATL.ARM"
            "Microsoft.VisualStudio.Component.VC.14.39.17.9.ATL.ARM.Spectre"
          )
          [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --add " +  $_}
          $Arguments = ('/c', "$env:VS_INSTALLER", 'modify', '--installPath', "`"$env:VS_INSTALL_PATH`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
          # should be run twice
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
