name: CI

on: [push, workflow_dispatch]

jobs:
  wsl:
    runs-on: windows-2019
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - uses: actions/checkout@v2
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
          set-as-default: 'true'
          wsl-shell-user: wsl
      - name: Show WSL environment
        shell: cmd
        run: wsl.exe --user root bash -c "env && cat /etc/sudoers && id wsl"
